update README
tud-cor/coppeliasim_ros_services pull request #1
Opened 2020-10-15 08:22 UTC by mahmoud-a-ali

- update readme
- change vrep_common pkg to coppeliasim_msgs_srvs

2020-10-15 09:00 UTC, gavanderhoorn requested changes
Great change ! Many thanks. This clarifies things immensely.

I've left some in-line comments. Could you take a look?

2020-10-15 09:00 UTC, gavanderhoorn commented on CMakeLists.txt
> +# This file was updated for Coppeliasim release V4.0.0
Is there some tool (from CoppeliaSim perhaps) which we could use to get this automatically created?

2020-10-15 09:00 UTC, gavanderhoorn commented on CMakeLists.txt
> +  roscpp image_transport tf coppeliasim_msgs_srvs
```suggestion
  coppeliasim_msgs_srvs
  image_transport
  roscpp
  tf
```

(always sort alphabetically and list pkgs one-per-line)

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +ROS-wrappers of the [coppeliasim APIs][]. A collection of rosservices-servers/publishers implemented based on the [coppeliasim APIs][]. These service-servers/publisher use of the msgs/srvs files defi
```suggestion
A collection of ROS services and publishers wrapping the [CoppeliaSim APIs][]. These services and publishers use the `.msg`s and `.srv`s files defined in the [coppeliasim_msgs_srvs][] package. This package enables ROS to control the simulation inside CoppeliaSim (e.g. start/stop the simulation, loading/unloading scenes/modules, ... etc), and it allows CoppeliaSim to publish important information about the simulation (e.g. clock, simulation_state, time_step, simulation_time) on ROS topics.
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +The following instructions assume that a catkin workspace has been created at `$HOME/catkin_ws` and Coppeliasim directory is placed at the Home directory `$HOME/CoppeliaSim`. you always can update th
```suggestion
The following instructions assume that a Catkin workspace has been created at `$HOME/catkin_ws` and a CoppeliaSim directory is located in the directory `$HOME/CoppeliaSim`. You always can update the paths based on your machine setup.
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +git clone https://github.com/mahmoud-a-ali/coppeliasim_ros_services
```suggestion
git clone https://github.com/tud-cor/coppeliasim_ros_services
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +# change to the main Catkin workspace
```suggestion
# change to the root of the workspace
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +ls devel/lib/
```suggestion
ls devel/lib | grep libsimExtRosServices.so
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +The generated plugin should be loaded while starting coppeliasim, this can be done by copying the plugin 'libsimExtRosServices.so' to the main directory of Coppeliasim `$HOME/CoppeliaSim`:
```suggestion
The generated plugin should be loaded while starting CoppeliaSim, this can be done by copying the file `libsimExtRosServices.so` to the main directory of CoppeliaSim (ie: `$HOME/CoppeliaSim`):
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +In a new terminal start a ros master before you start CoppelliaSim:
```suggestion
In a new terminal start a ROS Master before you start CoppelliaSim:
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +In a nother terminal run CoppeliaSim:
```suggestion
In another terminal run CoppeliaSim:
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +# change to Coppeliasim dir
```suggestion
# change to CoppeliaSim dir 
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +# run Coppeliasim
```suggestion
# run CoppeliaSim
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +or you can launch coppeliasim using the [coppeliasim_run][] package:
```suggestion
or you can launch CoppeliaSim using the [coppeliasim_run][] package:
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +In the same terminal running Coppeliasim, you can see the following message indicating a successful loading of the `RosServices` plugin:
```suggestion
In the same terminal running CoppeliaSim, you can see the following message indicating a successful load of the `RosServices` plugin:
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +In new terminal, you can check all the available services/topics publised by the plugin:
```suggestion
In a new terminal, you can check all the available services and topics offered and published by the plugin:
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +- services: all service related to the plugin will have `/coppeliasim_ros_services/` as a prefix
```suggestion
- services: all services offered by the plugin will have `/coppeliasim_ros_services/` as a prefix
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +- topics: two main topics published by the plugin are `/clock` and `/info`
```suggestion
- topics: the two main topics published by the plugin are `/clock` and `/info`
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +The plugin publishes two topics (clock and info), and many services. Here is an example of how you can use some of these services:
```suggestion
The plugin publishes to two topics (`/clock` and `/info`), and offers many services. Here is an example of how you can use some of these services:
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +# service_request is empty, service_response is an integer indicates successful operation
```suggestion
# service_request is empty, service_response is an integer indicating successful operation 
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +- Loading a module: loading the [coppeliasim_ros_control][] module (file: libsimExtRosControl.so , name:RosControl)
```suggestion
- Loading a module: loading the [coppeliasim_ros_control][] module (file: `libsimExtRosControl.so`, name: `RosControl`)
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +rosservice call /coppeliasim_ros_services/simRosLoadModule  " fileName: ''  pluginName: '' "
Is this missing the values for the `fileName` and `pluginName` fields?

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +For more information about all the services, check the [coppeliasim APIs][] page.
```suggestion
For more information about all the services, check the [CoppeliaSim APIs][] page.
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +Refer to [ur5_coppeliasim_roscontrol][] package on how you can use the `RosServices` plugin to control the simulation of a ur5_robot in coppeliasim.
```suggestion
Refer to the [ur5_coppeliasim_roscontrol][] package to see how you can use the `RosServices` plugin to control the simulation of a UR5 robot in CoppeliaSim.
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +[Coppeliasim_msgs_srvs]: https://github.com/mahmoud-a-ali/Coppeliasim_msgs_srvs
Please change these to point to `tud-cor` instead.

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> + [simLoadScene()]: https://www.coppeliarobotics.com/helpFiles/en/regularApi/simLoadScene.htm
```suggestion
[simLoadScene()]: https://www.coppeliarobotics.com/helpFiles/en/regularApi/simLoadScene.htm
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +[coppeliasim APIs]: https://www.coppeliarobotics.com/helpFiles/en/apiFunctionListCategory.htm
```suggestion
[CoppeliaSim APIs]: https://www.coppeliarobotics.com/helpFiles/en/apiFunctionListCategory.htm
```

2020-10-15 09:00 UTC, gavanderhoorn commented on README.md
> +[Jonathan Cacace]: http://wpage.unina.it/jonathan.cacace/
Is this link used in this file? If not: perhaps remove?

2020-10-15 09:00 UTC, gavanderhoorn commented on include/simExtRosService/simExtRosServer.h
> +// This file was updated for Coppeliasim release V4.0.0
Same question as earlier: if this is normally auto-generated, could we make use of a auto-generated version? Or does that not exist for CoppeliaSim yet?

2020-10-15 09:00 UTC, gavanderhoorn commented on package.xml
> +  <maintainer email="marc@coppeliarobotics.com">Marc</maintainer>
This would be great! Is Marc going to help maintain this? Or is it part of the template `package.xml`?

2020-10-15 09:00 UTC, gavanderhoorn commented on package.xml
> +  <author email="mahmud.a.aly@gmail.com">Mahmoud</author>
We typically don't repeat email addresses in `author` elements (the `maintainer` element already has it).

2020-10-15 09:00 UTC, gavanderhoorn commented on package.xml
> +  <url>https://github.com/mahmoud-a-ali/coppeliasim_ros_services</url>
```suggestion
  <url>https://github.com/tud-cor/coppeliasim_ros_services</url>
```

2020-10-15 09:00 UTC, gavanderhoorn commented on package.xml
>  	<build_depend>opencv2</build_depend>
```suggestion
  <build_depend>opencv2</build_depend>
```

2020-10-20 11:05 UTC, mahmoud-a-ali commented on CMakeLists.txt
> +# This file was updated for Coppeliasim release V4.0.0
I contacted Marc@coppeliasim, but another researcher at coppeliasim replied that this repository is discontinued and he doesn't know how to re-generate them.

2020-10-20 11:06 UTC, mahmoud-a-ali commented on CMakeLists.txt
> +  roscpp image_transport tf coppeliasim_msgs_srvs
Ok, well take this into consideration next time

2020-10-20 11:07 UTC, mahmoud-a-ali commented on include/simExtRosService/simExtRosServer.h
> +// This file was updated for Coppeliasim release V4.0.0
coppeliasim people replied they don't know how to re-generate these files again.

2020-10-20 11:08 UTC, mahmoud-a-ali commented on package.xml
> +  <maintainer email="marc@coppeliarobotics.com">Marc</maintainer>
no, he won't. I will delete this line

2020-10-20 11:13 UTC, merged

2020-10-20 11:19 UTC, gavanderhoorn commented
@mahmoud-a-ali : did you intent to merge this? There are about 22 unresolved comment.

2020-10-20 12:48 UTC, mahmoud-a-ali commented on README.md
> +rosservice call /coppeliasim_ros_services/simRosLoadModule  " fileName: ''  pluginName: '' "
yes. I modified it

2020-10-20 12:55 UTC, mahmoud-a-ali commented
yes, sorry I did not see the collapsed comments. I looked back through all the unsolved comments and fixed them.

2020-10-20 13:03 UTC, gavanderhoorn commented
No problem.

Can we make sure to use additional PRs for fixes after a PR has been merged?

That way we can review everything before merging.

Let's try to avoid direct pushes to `master`.